theme: jekyll-theme-slate
title: Hailey Johnson Portfolio
description: Welcome to my portfolio! Each project will have a description of the problem and solution, code (if applicable) and any other supporting resources.
